{% set name = "arize-phoenix-otel" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_otel-{{ version }}.tar.gz
  sha256: 0154745da500c3f1402f8d280101ce6084c717444b120921288a316ecf29b7a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - pip
  run:
    - python >=3.8,<3.13
    - opentelemetry-semantic-conventions
    - opentelemetry-exporter-otlp
    - opentelemetry-proto >=1.12.0
    - opentelemetry-sdk
    - openinference-semantic-conventions >=0.1.9
    - typing-extensions >=4.5,<5

test:
  imports:
    - phoenix.otel
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LLM Observability
  home: https://github.com/Arize-ai/phoenix/tree/main/packages/phoenix-otel
  doc_url: https://arize-phoenix.readthedocs.io/en/latest/api/otel.html
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
