{% set name = "arize-phoenix-otel" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_otel-{{ version }}.tar.gz
  sha256: 7717122db47744aa9da052bf5516e0b5061b38d8a5aecaf90f22ca7f88643b57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    - opentelemetry-semantic-conventions
    - opentelemetry-exporter-otlp
    - opentelemetry-proto >=1.12.0
    - opentelemetry-sdk
    - openinference-semantic-conventions >=0.1.9
    - typing-extensions >=4.5,<5

test:
  imports:
    - phoenix.otel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LLM Observability
  home: https://github.com/Arize-ai/phoenix/tree/main/packages/phoenix-otel
  doc_url: https://arize-phoenix.readthedocs.io/en/latest/api/otel.html
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
